echoserver: echoserver.cpp socklib.h socklib.cpp recv_line.h recv_line.cpp
	g++ -Wall -o echoserver echoserver.cpp socklib.h socklib.cpp recv_line.h recv_line.cpp

all: echoserver

clean: 
	rm -f *.o *~ echoserver